### ISSUE TITLE
Finer grain triggers?

### ISSUE THREAD

**Issue by sethgho** [square/sqlbrite#108] opened 2016-05-01 14:29 UTC
Here's the situation I'm running into: 
I've got one table that's especially noisy. All queries to that table are scoped to a particular `context_id` in the where clause. It's always being written to while knowing that `context_id` value. Ideally, my query Observable would only emit when the write is for the same `context_id`.  So this means I've got a situation where I know enough about the writes and the reads to reduce unnecessary query Observable emissions, but SqlBrite is making the assumption that I want to trigger for the whole table. We've mitigated the presentation effects of this so far by using throttling, hasStableIds in the RecyclerView destined queries, and other various forms of symptom suppression. But this means we're still performing potentially frequent unnecessary db reads, POJO/cursor allocations, etc.

With the overloaded `createQuery` method that already exists, I could theoretically create a query with two triggers: the context_id and the table name. This way, if we write in a way that would affect multiple `context_id`s, I'd still be able to fall back to the existing behavior and trigger the whole table.

Because the triggers in `BriteDatabase` are just Strings, this doesn't seem to me like too far of a stretch for SqlBrite's behavior. The only hurdles for me right now are a few assumptions being made by BriteDatbase's method signatures that the table and the trigger are the same value.

I see two possible solutions for my particular situation:

1. I could mirror much of the BriteDatabase trigger behavior in a wrapper class and manage my own finer grain triggers.
2. BriteDatabase could support explicit triggers in the insert/update/delete methods.

I'd appreciate anyone's thoughts on if this seems reasonable or if there's another solution altogether. Thanks!

**Comment by JakeWharton** [comment] 2016-05-01 16:20
Seems like a duplicate of #10. Can you add information to the existing issue so everything is in one place?

**Closed by JakeWharton** 2016-05-01 16:20 UTC
